import React from "react";
import { FooterContainer } from "../containers/footer";

function Marketing() {
  return (
    <div>
      <h1 className="marketing"></h1>
      <div className="term">
        <h1>Terms and Conditions</h1>
        <p>This document is an electronic record in terms of Information Technology Act and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.taxants.ca website and mobile application and mobile application only.</p>
        <p>The domain name www.taxants.ca (hereinafter referred to as "Website and mobile application") is owned by Taxants Inc Company incorporated under the Ontario Act, 1956 with its registered office in Ontario, Canada.</p>
        <p>Your use of the Website and Mobile App and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Website and mobile application including the applicable policies which are incorporated herein by way of reference. If you transact on the Website and mobile application, You shall be subject to the policies that are applicable to the Website and mobile application for such transaction. By mere use of the Website and mobile application, You shall be contracting with Taxants Inc, these terms and conditions including the policies constitute your binding obligations, with Taxants Inc.</p>
        <p>For the purpose of these Terms of Use, wherever the context so requires ‘You’ or “User” shall mean any natural or legal person who has agreed to become a member of the Website and mobile application by providing Registration Data while registering on the Website and mobile application as Registered User using the computer systems.</p>
        <p>Taxants Inc allows User to surf the Website and mobile application without registering on the Website and mobile application. The term “we”, “us”, “our” shall mean Taxants Inc. When You use any of the services provided by us through the Website and mobile application, You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website and mobile application following the posting of changes will mean that You accept and agree to the revisions.</p>
        <p>As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website and mobile application.</p>
        <p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by the Taxants Inc Privacy Policy.</p>
      </div>
      <div className="divide">
        <h3>TAXANTS PRODUCT PLATFORM</h3>
        <p>Taxants Inc is an intermediary and has provided a virtual platform through its website and mobile application (www.taxants.ca) enabling the users to buy any services listed on the website and mobile application (www.taxants.ca) at the price indicated therein at any time from any place.</p>
        <p>You understand, acknowledge and accept that the website and mobile application (www.taxants.ca) is only a mere facilitator and shall not be a party to or control in whatsoever manner any transactions between the service provider and the user.</p>
      </div>
      <div className="terms">
        <h3>THIRD PARTY SERVICE PROVIDER</h3>
        <p>You understand, agree and acknowledge that the Platform will engage independent third party accountant including but not limited to companies or organizations or individual service providers to perform these services mentioned on the website and mobile application (www.taxants.ca). Taxants Inc shall however, take responsibility in any manner for the work done by the service provider or its staff or any affiliates.</p>
        <p>The service provider or its staff or any affiliates used by Taxants are independent professionals, and Taxants shall have no responsibility in whatsoever manner for the money paid to them without informing Taxants.</p>
      </div>
      <div className="list">
        <h3>TERMS OF TAXANTS INC PLATFORM</h3>
        <ol>
          <li>
            <p>  All services offered on the website and mobile application (www.Taxants.ca) are offered by and agreed to between service provider and user. Taxants shall not endorse or advise or determine or involve in whatsoever manner in such services or terms of service including but not limited to any warranties, services, after service between the service provider and user.</p>
          </li>

          <li>
            <p> Taxants shall not in any manner be responsible for any non-performance or breach of any services between the user and service provider.</p>
          </li>
          <li>
            <p>   Taxants shall not make any representation to the services offered by the service provider on the website and mobile application www.Taxants.ca)</p>
          </li>
          <li>
            <p> Taxants shall not make any representation to the services offered by the service provider on the website and mobile application (www.Taxants.ca)</p>
          </li>
          <li>
            <p>  Taxants shall have no liability either direct or indirect in whatsoever manner for any articles broken, stolen or any injury the service provider or his staff or affiliate does in providing service to the customer.</p>
          </li>
          <li>
            <p>   The service provider or his staff or affiliate shall have their respective ID Proofs which they can share and also the photo of such provider delivering such service shall be given to the customer</p>
          </li>
          <li>
            <p>The grievances will be entertained, if made within 24 hours of delivering the service by the service provider.</p>
          </li>
          <li>
            <p>   You understand, acknowledge and accept that the payment shall be made in the mode as described by Taxants and in the event of non-compliance with the described mode of payment, Taxants shall have no control</p>
          </li>
          <li>
            <p> You understand, acknowledge and accept that the platform provided through the website and mobile application (www.Taxants.ca) shall not held liable in whatsoever manner for any but not limited to actions, commissions, misconduct, fraud or negligence of the service provider</p>
          </li>
        </ol>

      </div>
      <div className="use">
   <h3>TERMS OF USE</h3>
   <p>Use of the Site/Website and mobile application is available only to persons who can form legally binding contracts under Ontario Act. Persons who are "incompetent to contract" including minors, un-discharged insolvents etc. are not eligible to use the Site/Website and mobile application. If you are a minor i.e. under the age of 18 years, you shall not register as a member of the Taxants and shall not transact or use website and mobile application. As a minor if you wish to use or transact on website and mobile application, such use or transaction may be made by your legal guardian or parents on the Website and mobile application. Taxants reserves the right to terminate your Registration and / or refuse to provide you with access to the Website and mobile application if it is brought to Taxants notice or if it is discovered that you are under the age of 18 years.</p>
      <p>Privacy and use of personal and tax return information.</p>
      </div>
      <div className="general">
        <h3>General terms.</h3>
        <p>This Agreement is a complete statement of the agreement between you and Taxants Inc, and sets forth the entire liability of Taxants Inc., its affiliate accountants and your exclusive remedy with respect to the Service. The Services are protected by copyright, trade secret, and other intellectual property laws. You are only granted the right to use the Services and only for the purposes described by Taxants. Taxants Inc. reserves all other rights in the Services. You agree not to use, nor permit any third party to use, the Services or content in a manner that violates any applicable law, regulation or this Agreement. You agree you will not:</p>
       <ul>
         <li>
           <p> Provide access to or give any part of the Services to any third party.</p>
         </li>
         <li>
           <p> Reproduce, modify, copy, deconstruct, sell, trade or resell the Services.</p>
         </li>
       </ul>
       <p>How and why we use personal information.</p>
       <p>Taxants Inc. collects personal information about you so that we can effectively provide the services and products to you that you have requested (including completing and filing your income tax return), establish your identity, manage our operations, make our services more useful and intelligent, and comply with legal and regulatory requirements. And, if we need to use your personal information for any other purpose, we will identify that purpose to you.</p>
       <p>We may also use your personal information to enable us to understand your needs and preferences and then to alert you by mail, phone, e-mail or other electronic messaging to current and future product offerings, and to tailor marketing material to your specific needs. You may choose not to receive these materials at any time by unsubscribing to our emails.</p>
       <p>Consent to the collection, use or disclosure of personal information.</p>
        <p>We may obtain your express consent in writing, through electronic means, or verbally. Your consent may also be implied by an action that you have taken. You can always refuse or withdraw your consent to the collection, use or disclosure of your personal information. Doing so may, in some cases, mean that we will be unable to provide you with the product or service that you have requested.</p>
 

      </div>
      <div className="closure">
  <h3>Disclosure of personal information.</h3>
  <p>We do not disclose your personal information to third parties except as described in this Privacy Policy, with your consent, or as permitted or required by law. Your personal information may be disclosed:</p>
      <ul>
        <li>
          <p>to outside suppliers employed or retained by us to perform certain services or functions on our behalf, including billing, processing of credit and debit card transactions, mailing and data processing, shredding and storage, and collection or research or analytics services. We select our outside suppliers carefully and insist that they have privacy and security standards that meet our strict requirements. We provide to these suppliers only the personal information required for them to perform the services or functions for which they have been engaged. We require them to retain any personal information in strictest confidence and we also restrict their use of your personal information to what is necessary to act on our behalf;</p>
        </li>
        <li>
          <p>    to Taxants Inc. and its affiliate partners to deliver or provide a product or service that you have requested, including Instant Cash Back;</p>
        </li>
        <li>
          <p>    to Taxants Inc. and its affiliate partners to offer you products and services which may be of interest to you (though you may of course choose not to receive these materials, as noted above);</p>
        </li>
        <li>
          <p> in the event of a sale or transfer of our business or assets.</p>
        </li>
      </ul>
      </div>
      <div className="closure">
        <h3>Protecting personal information.</h3>
        <p>We view protection of Your privacy as a very important principle. We understand clearly that You and Your Sensitive Personal Information is one of our most important assets. We store and process Your Sensitive Personal Information including any sensitive financial information collected (as defined under the Information Technology Ac), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act and Rules there under. Our Privacy Policy is available for more details.</p>
        <p>What you can do to manage your privacy and communications.</p>
        <p>Accuracy of Personal Information and Access.</p>
        <p>It is important that the personal information we have is accurate, complete and up to date. To this end, you are encouraged to inform us when there are any changes to your information.</p>
        <p>You may also, at any time, contact us through support@taxants.ca to request access to your personal information, verify its accuracy and, if required, correct it. Taxants Inc. will provide you with access to your personal information except where we are prohibited by law from doing so, or are permitted by law to restrict your access and have legitimate reasons for doing so. We may charge you a fee to provide access to your information and will let you know in advance if there will be a charge for doing so.</p>
        <p>The contact information for our support team is as follows:</p>
        <p>By e-mail: support@taxants.ca</p>
        <p>In addition, as noted above, you can refuse to provide personal information to us and you may also at any time, on reasonable notice to us, in person or via telephone or e-mail, withdraw your consent to the collection, use or disclosure of any of your personal information, unless it is required to provide you with the services you have requested or to provide you with necessary information relating to your accounts with us or as required by law.</p>
        <p>Managing Communications From Us.</p>
        <p>We will honour your choices when it comes to receiving electronic communications from us. Your communication preferences will be changed within 10 business days with no charge to you.</p>
        <p>You have the following choices for managing your communication preferences:</p>
        <ul>
          <li>
            <p>  You can change your marketing preferences by sending your request via e-mail, including the contact information to which you no longer wish to receive communications and the details of which types of communications you no longer wish to receive, to support@taxants.ca;</p>
          </li>
          <li>
            <p> To unsubscribe from all marketing materials click the unsubscribe link in the e-mail or newsletter you received;</p>
          </li>
          <li>
            <p>   Contact us at support@taxants.ca to provide us with details of which communications you wish to opt-out of;</p>
          </li>
          <li>
            <p>  Subject to your control, our mobile application may send push notifications to your mobile device. If you are receiving push notifications and no longer wish to receive these types of communications, you may turn them off at the device level.</p>
          </li>
          <p>Remember that even if you choose not to receive marketing communications from us, we will continue to send you mandatory service or transactional communications.</p>
          <p>Cookies and other tracking technologies.</p>
          <p>In addition, we, or our third party advertisers, may collect information online through the use of "cookies", web beacons and other technologies. These technologies are small pieces of information/text sent by a web server to be stored on a user's web browser so it can later be read back from that browser on subsequent visits to a website. We use these technologies to store visitors' preferences, understand how you navigate through and process content on our website, and to record session information which allows us to customize our website for you as you visit various components of www.taxants.ca. Through the use of cookies, we can display items that may be of interest to you, or make it easier for you to access your account information.</p>
          <p>We do not link the information we store in web technologies to any personal information you provide while on our site. You may be able to configure your browser to accept or reject all or some cookies, or to notify you when a cookie is set, however, cookies must be enabled in order to access most functions on the site. Since each browser is different, please check the "Help" menu of your browser to learn how to change your web technology preferences.</p>
          <p>Our website may include third party-delivered advertisements or links to third-party websites. These third party websites may serve ads that assign different web technologies to you. Those web technologies may be used to track your involvement with the advertising site. You may choose not to accept these web technologies. We do not control these third parties or their use of website technologies, and you should review their privacy policies to learn more about whether they collect and use your personal information in connection with the information their web technologies gather from you, including what, why and how they collect and use your personal information.</p>
          <p>You may also opt-out of network advertising programs that track your activities across multiple websites to deliver personalized advertising content to you. You will still receive other types of advertising; however, it will not be based on your interests. Deleting browser cookies and web beacons can remove your opt-out preferences, so you should use these tools periodically to ensure that your preferences are up-to-date.</p>

        </ul>
      </div>
      <div className="closure">
        <h3>Accountability.</h3>
        <p>Taxants Inc is accountable for our compliance with this Privacy Policy and applicable privacy legislation. We regularly monitor our security measures and procedures to ensure that they are effective and properly administered. If you have any questions about this Privacy Policy, our practices, our have a complaint or concern, please contact us at support@taxants.ca. Taxants Inc. will promptly investigate all complaints and if found justified, will take appropriate measures including amending its policies and practices.</p>

      </div>
      <div className="closure">
        <h3>REFUND AND CANCELLATION POLICY</h3>
        <p>A refund policy may be provided for each service separately. In case, the service is eligible for a refund, then the same shall be done in 30 days. If service or services are not utilized and in case if You are not available at the time of the service, then a “no-show” fee shall be levied and the amount shall be refunded.</p>
        <p>In the event of cancellation, the refund policy provided shall be applicable. You cancel the service 24hrs prior to the delivery of service with no charges. In case cancelled after the said period, a service fee of $20 CAD + HST shall be collected and the balance amount shall be refunded.</p>
        <p>In case, the service provider or his staff or affiliate cannot accomplish the service, then a new service person may be provided to You.</p>
        <br></br><br></br>
        <p>Tax tips.</p>
        <p>We post tips based on different scenarios that may be relevant to your tax situation, based on your situation. These tips are based on rules and regulations communicated by the Canada Revenue Agency (CRA) and Revenu Quebec in connection with the filing of personal tax returns for the relevant tax year. It is up to you to determine if the information provided is relevant to or will benefit your specific tax situation, and whether to update your tax return prior to filing. Tax Tips are generated automatically, and are not individualized tax advice; they are only intended as ideas for a user. Taxants Inc. assumes no liability for, and will not be responsible for any incorrect or inaccurate filings based upon Tax Tips.</p>
        <p>The feature is exclusively valid for the tax year when you purchase it and available in returns for which it is purchased for.</p>
        <p>Email support.</p>
        <p>Use our chat feature to reach one of our technical support team members during tax season. Email support is available Monday to Sunday 9:00 am to 9:00 pm EST.This feature is only available in returns for which it is purchased for.</p>
        <p>Return storage.</p>
        <p>A copy of the data in your tax return will be stored electronically by the affiliate accountant for seven years, from the date of filing. At your request, it will be retrieved in PDF or other format (at accountant’s discretion). You may request a copy of your tax return data at any time during the storage period by emailing support@taxants.ca. Accountant may, in its sole discretion, require a signed authorization form to validate the request in order to ensure your information protected. This feature is only available in returns for which it is purchased for.</p>
        <p>Limitation of liability and damages.</p>
        <p>Pursuant to Canada Revenue Agency (CRA) guidance, be advised that any federal tax advice given to you, including anything provided to you in writing, is not intended to be used, and it cannot be used, by any person or entity for the purpose of avoiding penalties imposed under the Canadian Income Tax Act and Regulations.</p>
        <p>Any advice provided to you by an accountant will be based on information you provide in your tax return. You understand and agree that the Taxants and the accountant is not able to verify the information you provide, and that if you provide incorrect or incomplete information, the advice provided to you may not be accurate. You have sole responsibility for reviewing your tax return(s), documentation or adjustment and confirming their overall accuracy and completeness prior to submitting to CRA or Revenu Québec. You agree not to hold Taxants Inc. and affiliate accountants liable for any loss or damage incurred as a result of your use of any Service. Additionally, except for the reimbursement for errors expressly set out in this Agreement, Taxants Inc. assumes no liability whatsoever related to the Service.</p>
        <p>Changes.</p>
        <p>Taxants Inc. reserves the right to change this Agreement at any time, and the changes will be effective when posted through the Services, on the Taxants Inc. website for the Services or when Taxants Inc notifies you by other means. Taxants may also change or discontinue offering the Services, in whole or in part. Your continued use of the Services indicates your agreement to the changes.</p>
      </div>
      <div className="closure">
        <h3>LEGAL ACTION AGAINST THE SERVICE PROVIDER</h3>
        <p>In the event of any criminal act committed by the service provider or its staff or affiliate accountant while providing services, You may take direct action under the laws of the country on such service provider or its staff or affiliate and in such cases Taxants shall also be informed about the same.</p>
        <p>In the occurrence of the any such event mentioned above, You shall not make Taxants a party to such offence, as the service provider or its staff or affiliates are individually and severally liable for any criminal act committed by him or her.</p>

      </div>
      <div className="closure">
        <h3>WARRANTIES AND LIABILITY</h3>
        <p>This Website and mobile application, all the materials and products (including but not limited to software) and services, included on or otherwise made available to You through this site are provided on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Taxants do not warrant that:</p>
        <p>This Website and mobile application will be constantly available, or available at all; or The information on this Website and mobile application is complete, true, accurate or non-misleading.</p>
        <p>Taxants will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website and mobile application.</p>
        <p>Taxants do not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website and mobile application; their servers; or electronic communication sent from us are free of viruses or other harmful components.</p>
        <p>Nothing on Website and mobile application constitutes, or is meant to constitute, advice of any kind.</p>
        <p>You will be required to enter a valid name, phone number, email id, address, while availing any of the services mentioned on the Website and mobile application. By registering your phone number with us, You consent to be contacted by us via phone calls and / or Text Messages notifications, in case of any service related updates. We will not use your sensitive personal information to initiate any promotional phone calls or Text Messages.</p>
      </div>
      <div className="closure">
        <h3>CREDIT CARD PAYMENT</h3>
        <p>Your credit card details shall be transferred directly to our payment service provider Stripe for immediate authorization and are not recorded or stored in our database. Once we have received authorization from the payment service provider, we shall confirm your service order.</p>
        <p>Further:</p>
        <ol>
          <li>
            <p>  Use of the payment facility shall not render Taxants liable or responsible for either the non–delivery of service, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after service warranty or fraud as regards the services listed on Taxants Website and mobile application.</p>
          </li>
          <li>
            <p>
            You have categorically authorized Taxants or its service providers to collect, process, facilitate and remit payments and / or the Transaction Price electronically from other Users in respect of transactions through Payment Facility. Your relationship with Taxants is on a principal to principal basis and by accepting these Terms of Use you agree that Taxants is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed on Taxants Website and mobile application that are paid for by using the Payment Facility. Taxants does not guarantee the identity of any User nor does it ensure that a User or a Seller will complete a transaction.</p>
          </li>
          <li>
            <p>  You understand, accept and agree that the payment facility provided by Taxants is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, collection and remittance facility for the Transactions on the Taxants Website and mobile application using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility, Taxants is neither acting as trustees nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price</p>
          </li>
          <li>
            <p>Taxants reserves the right to impose limits on the number of Transactions or Transaction Price which Taxants may receive from on an individual Valid Credit/ Debit/PrePaid Card and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual User during any time period, and reserves the right to refuse to process Transactions exceeding such limit.</p>
          </li>
          <li>
            <p>  Taxants reserves the right to refuse to process Transactions by Users with a prior history of questionable charges including without limitation breach of any agreements by User with Taxants or breach / violation of any law or any charges imposed by Issuing Bank or breach of any policy.</p>
          </li>
          <li>
          <p>  Taxants may do such checks as it deems fit before approving the receipt of/ user’s commitment to pay (for Cash On Delivery transactions) Transaction Price from the User for security or other reasons at the discretion of Taxants. As a result of such check if Taxants is not satisfied with the creditability of the User or genuineness of the Transaction / Transaction Price, it will have the right to reject the receipt of / Users commitment to pay Transaction Price.</p>
          </li>
          <li>
            <p>  Taxants may delay notifying the payment confirmation, if Taxants deems suspicious or for Users conducting high transaction volumes to ensure safety of the Transaction and Transaction Price. In addition, Taxants may hold the service and may not provide service at the request of law enforcement officials or in the event the user is engaged in any form of illegal activity.</p>
          </li>
          <li>
            <p>  The user acknowledge that Taxants will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction / Transaction Price or any delay in processing a Transaction / Transaction Price which is beyond control of Taxants.</p>
          </li>
        </ol>

      </div>
      <div className="closure">
        <h3>LEGAL DISCLAIMER</h3>
        <p>If Taxants has suspicion or knowledge, that any of its users and sellers are involved in any activity that is intended to provide claims or information that is false, misleading or not genuine, then Taxants may while reserving its rights to initiate civil and/or criminal proceedings against member may also at its sole discretion suspend, block, restrict, cancel the Display Name of such user and seller and /or disqualify that user and any related users from availing protection through this program.</p>
      <p>Taxants reserves its right to initiate civil and/or criminal proceedings against a user who, files a invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the legal proceedings as aforesaid,Taxants may at its sole discretion suspend, block, restrict, cancel the Display Name [and its related Display Names] of such user and/or disqualify that user and any related users from availing protection through this program. Any person who, knowingly and with intent to injure, defrauds or deceives, files a Fraudulent Complaint containing false, incomplete, or misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent of the law.</p>
      <p>We may at any time at our sole discretion reinstate suspended users. A user that has been suspended or blocked may not register or attempt to register with us or use the Website and mobile application in any manner whatsoever until such time that such user is reinstated by us. Notwithstanding the foregoing, if You breach the Terms of Use or Privacy Policy or other ruler and policies, we reserve the right to recover any amounts due and owing by You to us and to take strict legal action including but not limited to a referral to the appropriate police or other authorities for initiating criminal or other proceedings against You.</p>
      </div>
      <div className="closure">
        <h3>INDEMNITY</h3>
        <p>You shall indemnify and hold harmless Taxants, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
      </div>
      <div className="closure">
        <h3>APPLICABLE LAW / JURISDICTION</h3>
        <p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of Canada. The place of jurisdiction shall be Mississauga, Ontario.</p>
      </div>
      <div className="closure">
        <h3>INTELLECTUAL PROPERTY POLICY (IP POLICY)</h3>
        <p>All existing and future Intellectual Property in the nature of unregistered or registered rights to any and all patents, copy rights, trademarks of the website and mobile application (www.taxants.ca) shall be the sole property of Taxants Inc.</p>
        <p>All material on this site, including images, pictures are protected by copyrights, trademarks, and other intellectual property rights. Material on Website and mobile application is solely for your personal, non-commercial use. Any logos, product images belong to their respective owners.</p>
        <p>Taxants uses such marks, logos, product images solely for promotional purposes and shall have no intention in whatsoever manner to acquire any intellectual property rights belonging to third parties.</p>
        <p>You acknowledge and agree not to use, reuse, and challenge any application, registration of any marks, anywhere in the world. You shall not copy, reproduce, republish, upload, post, transmit or distribute such logos, images, marks in any way, including by e-mail or other electronic means and whether directly or indirectly and You must not assist any other person to do so.</p>
        <p>Without the prior written consent of the owner, modification of the materials, use of the materials on any other web site or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>
      </div>
      <div className="closure">
        <h3>INTELLECTUAL PROPERTY RELATED ISSUES</h3>
        <p>Taxants Inc respects the intellectual property of others. In case, you feel that Your Intellectual Property Right has been infringed, you can send an email to support@taxants.ca</p>
      </div>
      <div className="closure">
        <h3>SERVICE DESCRIPTION</h3>
        <p>Taxants do not warrant that service description or other content of this Website and mobile application is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.</p>
      </div>
      <div className="closure">
        <h3>LIMITATION OF LIABILITY</h3>
        <p>IN NO EVENT SHALL TAXANTS INC BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>
        <p>www.taxants.ca may include inaccuracies and typographical errors. Changes and improvements are periodically made to the site and the information therein. We do not warrant or assume any legal liability or responsibility for the completeness, or usefulness of any information, service. Information received via this website and mobile application should not be relied upon for personal, legal or financial decisions.</p>
      </div>
      <FooterContainer />
    </div>
   
  );
}

export default Marketing;
